apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-blueprints-doc
  title: RHDH Blueprints Documentation
  description: Documentation for Red Hat Developer Hub Blueprints
  annotations:
    github.com/project-slug: your-org/rhdh-blueprints-doc
    backstage.io/techdocs-ref: url:https://github.com/rh-ita-ssa-devhub-org/rhdh-blueprints-doc
  tags:
    - documentation
    - rhdh
    - blueprints
spec:
  type: documentation
  lifecycle: production
  owner: user:default/user1


